#!/usr/bin/sh
#

umask 022
unalias -a

pushd() { command pushd "$1" > /dev/null; }
popd() { command popd "$1" > /dev/null; }
msg() { printf "\033[1;34m::\033[0m %s\n" "$@"; }
warn() { printf "\033[1;33m::\033[0m %s\n" "$@"; }
die() { printf "\033[1;31m::\033[0m %s\n" "$@"; exit 1; }

check_root() {
	if [[ $EUID -ne 0 ]]; then
		die "You must be root to run 'ataraxia-install'"
	fi
}

main() {
	local keyboardmap="us"
	local timezone="America/New_York"
	local hostname="ataraxia"
	local efi efibitness rootdevice services confirm mklabel bootfs

	while getopts d:k:t:h:s: opts; do
		case $opts in
			d) rootdevice="$(realpath $OPTARG)" ;;
			k) keyboardmap="$OPTARG" ;;
			t) timezone="$OPTARG" ;;
			h) hostname="$OPTARG" ;;
			s) services="$OPTARG" ;;
		esac
	done
	shift $((OPTIND - 1))

	check_root

	[ ! -b "$rootdevice" ] && die "You haven't set the device name"

	msg "Installing Ataraxia Linux on $rootdevice"
	read -p "Continue [y/N]: " -r confirm
	case $confirm in
		y|Y) true ;;
		n|N|*) exit 0 ;;
	esac

	msg "Searching for install media"
	if ! mountpoint -q /run/live-os; then
		die "Seems the initramfs is not mounted. Mount manually"
	fi

	if [ -d "/sys/firmware/efi" ]; then
		efi="yes"
		efibitness="$(cat /sys/firmware/efi/fw_platform_size)"
	else
		efi="no"
	fi

	msg "Creating partitions"
	if [ "$efi" == "yes" ]; then
		mklabel="gpt"
		bootfs="fat"
	else
		mklabel="msdos"
		bootfs="ext4"
	fi

	wipefs -afq "$rootdevice"
	parted -s "$rootdevice" mklabel $mklabel
	parted -a optimal -s "$rootdevice" mkpart primary 2mb 256mb
	parted -a optimal -s "$rootdevice" mkpart primary 256mb 100%
	[ "$mklabel" == "msdos" ] && parted -s "$rootdevice" set 1 boot on
	[ "$mklabel" == "gpt" ] &&   parted -s "$rootdevice" set 1 esp on
}

main "$@"

exit 0

